### PR TITLE
Add --version flag

### PR DESCRIPTION
**Pull request by chr4**
I found this useful, because I wasn't always sure which version I'm at. 

Let me know if you prefer some adjustments!

### CODE REVIEW

**Comment by terjesannum** [comment]
The version is already printed in the log on startup, is this really necessary?

**Comment by chr4** [comment]
Well, it's your choice. But I think having a `--version` is a good practise to have. 

It doesn't show the version upon startup for me, at least not with a valid config? Some automations rely on version checks (e.g. when automatically updating once a version get's out of date).

```
$ tibber-exporter
2023/12/04 20:30:30 Starting tibber-exporter (https://github.com/terjesannum/tibber-exporter)
2023/12/04 20:30:30 Error getting homes: Message: 400 Bad Request; body: "{\"errors\":[{\"message\":\"Context creation failed: no token specified\",\"extensions\":{\"code\":\"UNAUTHENTICATED\"}}]}\n", Locations: [], Extensions: map[code:request_error]. Exiting...
```

Also, this patch adds the current version as a Prometheus metic, which might also be nice to have (when e.g. running a fleet of exporters).

**Comment by terjesannum** [comment]
If you run your own build you don't get any version, that is set by the github action and present in the prebuilt binaries and docker image:
https://github.com/terjesannum/tibber-exporter/blob/806e1870508e8221d5af670fd4e72f9d869b0d15/.github/workflows/release.yaml#L40
https://github.com/terjesannum/tibber-exporter/blob/806e1870508e8221d5af670fd4e72f9d869b0d15/.github/workflows/release.yaml#L103

I have no problem with adding a `--version` option, and having it as a metric too is a nice feature. But it should then use the same mechanism used to set the version in the user-agent and don't be a constant in the source code.

**Comment by chr4** [comment]
You're right, I'm using nixOS which builds my exporters automatically.

I agree that using the same procedure is nice, but I'm not sure if that's possible in a way that works with Github actions as well as with a default GO build. Maybe an environment variable?

I've also noticed that https://github.com/terjesannum/tibber-exporter/blob/master/charts/tibber-exporter/Chart.yaml#L3 uses a hardcoded version, too?

**Comment by chr4** [comment]
Other popular exporters, like [postgres_exporter](https://github.com/prometheus-community/postgres_exporter/blob/master/VERSION) or [node_exporter](https://github.com/prometheus/node_exporter/blob/master/VERSION) use a central VERSION file.

**Comment by terjesannum** [comment]
Not much different from here really. The version is consistent in all artifacts, but the source is the version in the helm chart not a separate file.
If you want to set a version in your go build, just use `-ldflags '-X main.userAgent=tibber-exporter/x.x.x'`

**Comment by terjesannum** [comment]
But I agree that having it in a VERSION file is more intuitive :)

**Comment by chr4** [comment]
I've added `main.userAgent` ldflag to my build process, and it seems to work!

A more lightweight alternative might be to implement `--version` like this:

```go
	if userAgent == "" {
		userAgent = "tibber-exporter (https://github.com/terjesannum/tibber-exporter)"
	}

	if *showVersion {
		fmt.Printf("%s\n", userAgent)
		os.Exit(0)
	}
```

What do you think?

**Comment by terjesannum** [comment]
I like your idea of also getting the version in a build_info metric, so I think I will merge this as it is and make the necessary adjustments in the build workflow. Thanks

**Comment by terjesannum** [comment]
I think everything is ready now. If you do your own build, there is now a Makefile which should set all the ldflags for you

**Pull request merged**
